### ISSUE TITLE
Panic if hit `ENTER` with no bookmarked patchsets

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/patch-hub#12]
### **Description**:

In the "Bookmarked Patchsets" screen, the program panics if there are no bookmarked patchsets, and the user hits `ENTER` as if it were to choose a bookmarked patchset.

### **How to reproduce**:

1. Go to the "Bookmarked Patchsets" screen (you must have at least one bookmarked patchset for this)
2. Unbookmark every patchset to end up with an empty list (see screenshot 1 below)
3. Hit the `ENTER` key
4. Notice that the program panics (see screenshot 2 below)

### **Expected behavior**:

This panic shouldn't happen. Actually, it would be better to notify the user that there are no bookmarked patchsets and revert to the "Mailing List Selection" screen (or just revert to it).

### **Screenshots**

Screenshot 1:

![2024-07-26-013712_1723x937_scrot](https://github.com/user-attachments/assets/275a0ae5-1456-4943-bf53-a8a14a7d0b90)

Screenshot 2:

![2024-07-26-013756_855x553_scrot](https://github.com/user-attachments/assets/d520832f-6c27-4b43-a74a-9f0a2c2c7cf5)

### **Setup**:

- Project branch: unstable
- Project commit hash: aff5c1ffd85d491fd4c290d0e439e4215ae07a5c
- `rustc` version: 1.79.0
- `cargo` version: 1.79.0

**Comment by th-duvanel** [comment]
I'm currently working on this.
