### ISSUE TITLE
Add configurations through persistent files

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/patch-hub#23]
### **Description**:

`patch-hub` only provides configuration through environment variables, e.g., `KW_CACHE_DIR`, `KW_DATA_DIR`, and `PATCH_HUB_PAGE_SIZE`. We should also provide configuration through persistent files.

Ideally, it would be nice if they follow the `kw` convention for the config files, but a `.json` would surely work better. We must assess whether the configs isolated from `kw` would work.

### **Motivation**:

Solely using env vars for configurations is very limiting for the user, so persistent files that can be later transmitted between installations give the project more versatility.

### **Version**

Branch: `unstable`
Commit: e18e895

**Comment by OJarrisonn** [comment]
Some rust cli tools use a `.toml` as config file rather than a `.json`. Of course this isn't mandatory.
