### ISSUE TITLE
Extract fetch first page of "Latest Patchsets from" from key-event handling

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/patch-hub#29]
### **Context**:

As you can see [here](https://github.com/kworkflow/patch-hub/blob/aa47efd7b3e0f155ecc40c3fb4799c5775218e3f/src/main.rs#L62), when going from the "mailing list selection" screen to "latest patchsets from", we make a call to `fetch_current_page` to fill the first page of the screen.

### **Proposal**:

To keep handling key events separated from handling conditions independent from events, we could extract it to this [match](https://github.com/kworkflow/patch-hub/blob/aa47efd7b3e0f155ecc40c3fb4799c5775218e3f/src/main.rs#L36) when the number of processed patchsets is empty.

### **Setup**:

- Project branch: unstable
- Project commit hash: aa47efd

**Comment by th-duvanel** [comment]
I can do this.
