### ISSUE TITLE
Standardize the use of `usize` for unsigned integers

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/patch-hub#35]
### **Context**:

Throughout the project, we use `u32` for unsigned integers.

### **Proposal**:

Everywhere, `usize` is used, which makes us do a lot of casting with `as usize` or `as u32`, so standardize the use of `usize` to the detriment of `u32`.

### **Setup**:

- Project branch: unstable
- Project commit hash: 012828367
- `rustc` version: 1.79.0
- `cargo` version: 1.79.0

**Comment by th-duvanel** [comment]
I can do this.
