### ISSUE TITLE
Log missing external dependencies

### ISSUE THREAD

**Issue by OJarrisonn** [kworkflow/patch-hub#48]
### **Description**:

Some external dependencies like `b4` or `delta` (coming soon) might be missing. Sometimes those dependencies are mandatory and currently patch-hub doesn't quite inform properly this to the user on the runtime. 

### **Motivation**:

Always logging important errors in a readable way improves a lot the program from the user-friendly perspective

**Comment by davidbtadokoro** [comment]
True! Especially `b4`, which is a hard dependency and causes ugly crashes if we don't have it. Currently, most (if not all) first users will face this problem, and the error message won't even indicate the real cause of the error. Thanks for documenting this :pray:

**Comment by CanNuhlar** [comment]
A real world example of what @davidbtadokoro said.

`Error:
   0: No such file or directory (os error 2)

Location:
   src/app.rs:129

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.`

I thought it's crashing but turns out `b4` was missing and I'm a first time user

**Comment by davidbtadokoro** [comment]
> A real world example of what @davidbtadokoro said.
> 
> ```
> Error:
>    0: No such file or directory (os error 2)
> 
> Location:
>    src/app.rs:129
> 
> Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> Run with RUST_BACKTRACE=full to include source snippets.
> ```
> 
> I thought it's crashing but turns out `b4` was missing and I'm a first time user

Hey @CanNuhlar, and thank you for the report! Also, thank you for giving `patch-hub` a try :smile: 

Going to work on this ASAP, as this is an ugly crash indeed...
