### ISSUE TITLE
`patch-hub --show-configs`

### ISSUE THREAD

**Issue by OJarrisonn** [kworkflow/patch-hub#60]
### **Description**:

A flag for `patch-hub` that shows the configs the app is using. 

### **Motivation**:

The settings being used may be different from the ones in the config file if the user misspell something or used an environment variable.

This would help users understand why the execution is behaving differently from the setted configurations.

**Comment by davidbtadokoro** [comment]
Thanks for the update! Change merged into the unstable branch :+1:
