### ISSUE TITLE
Add entry in "Edit Config" screen for max log age

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/patch-hub#72]
### **Description**:

There is a config called `max_log_age` for determining how long logs produced by `patch-hub` will live on the user fs (the app cleans them at start-up using this value). Add an entry in the "Edit Config" screen for it.

### **Motivation**:

This configuration is invisible for the user that only uses `patch-hub` and doesn't goes deeper into the inner configurations of it.

**Comment by gabrielsrd** [comment]
I will take a look at this

**Comment by gabrielsrd** [comment]
I've created a pull request for this
